### ISSUE TITLE
CSS box-sizing

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-developer-tools#16]
I know, that this is not an error at all, but:

If I use bootstratp CSS, for example - there present this style definition:

``` css
/* bootstrap.css #259 */
* {
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
}
```

So with this borders I've got some irritating behavior when mouseover on some ZendTools button and popup content showed over button and I'm trying move my mouse to this content - it disappears!

Because of borders adds some extra space and mouseover event brokes.
Works if I move mouse over green arrow :)

I know, that this is behavior of bootstrap.css, but if u will add this:

``` css
#zend-developer-toolbar {
...
    -webkit-box-sizing: content-box;
    -moz-box-sizing: content-box;
    box-sizing: content-box;
...
}
```

then problem will be fixed on all possible CSS frameworks, I think.

Sorry for my english.
Thx

---

Originally posted by @man4red at https://github.com/zendframework/zend-developer-tools/issues/145

**Comment by weierophinney** [comment]
please see : https://github.com/zendframework/ZendDeveloperTools/pull/124


---

Originally posted by @mpalourdio at https://github.com/zendframework/zend-developer-tools/issues/145#issuecomment-38991348

**Comment by weierophinney** [comment]
@mpalourdio , thx :+1: 


---

Originally posted by @man4red at https://github.com/zendframework/zend-developer-tools/issues/145#issuecomment-38991378

**Comment by weierophinney** [comment]
@mpalourdio, I think, that:

``` css
#zend-developer-toolbar {
...
    -webkit-box-sizing: content-box;
    -moz-box-sizing: content-box;
    box-sizing: content-box;
...
}
```

would be preferable because of cross browser compatibility


---

Originally posted by @man4red at https://github.com/zendframework/zend-developer-tools/issues/145#issuecomment-38991539
